language: java
jdk: openjdk13

# install:
#   - mettre une commmande si nécessaire

matrix : 
  include : 
    - os: linux
      script :
        - cd lab2 && mvn package
        - cd .. && cd lab1 && mvn package
    - os: osx 
      script :
        - cd lab2 && mvn package
        - cd .. && cd lab1 && mvn package      
        

