language: java
jdk: openjdk13

# install:
#   - mettre une commmande si nécessaire

os : 
  - linux
  - osx
env :
  matrix : 
    - TARGET : "lab1"
    - TARGET : "lab2"
    - TARGET : "lab3"
    - TARGET : "lab4"
    - TARGET : "lab5"
script :
  - if [ "$TARGET" = "lab6" ]; then
    # download jdk-14
    wget https://github.com/forax/java-next/releases/download/untagged-c59655314c1759142c15/jdk-14-loom-linux.tar.gz
    # extract
    tar xvf jdk-14-loom-linux.tar.gz
    # export new environment variable JAVA_HOME
    export JAVA_HOME=$(pwd)/jdk-14-loom/
fi
  - cd $TARGET && mvn package 
