language: java
jdk: openjdk13

# install:
#   - mettre une commmande si nécessaire
os:
  - linux
  - osx
matrix : 
  include : 
    - script: cd lab2 && mvn package
    - script: cd ../lab1 && mvn package
